name: Node.js tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
      - name: Setup Node - version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Archive tool cache
        run: |
          mkdir -p "${{ runner.tool_cache }}/${{ matrix.node-version }}"
          cd "${{ runner.tool_cache }}/${{ matrix.node-version }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ runner.tool_cache }}/${{ matrix.node-version }}/tool_cache.tar.gz
